### ISSUE TITLE
Cant install from carthage or cocoapods

### ISSUE THREAD

**Issue by HalidCisse** [hyperoslo/Keychain#10]
Podfile => [!] Unable to find a specification for `Keychain`
Carthage => No tagged versions found for github "hyperoslo/Keychain"

**Comment by onmyway133** [comment]
@HalidCisse Keychain is not officially released yet. In the meantime, you can use

Cocoapods

```
pod 'Keychain', :git => 'https://github.com/hyperoslo/Keychain.git'
```

Carthage

```
github "hyperoslo/Keychain" "master"
```

**Comment by HalidCisse** [comment]
Thanks !!
