### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Keychain#2]
I've been thinking about the public API, does it have to reference the pod name or could we call the main struct `Keychain` instead to make it more implicit to what it actually does?

So instead of;

``` swift
Stash.password(service, account: account)
```

We would get

``` swift
Keychain.password(service, account: account)
```

Also, maybe the `service` should be the second argument and have it default to the application bundle identifier so that you don't have to set it.

``` swift
Keychain.password(forAccount: account)
```

What do you guys think? @RamonGilabert @vadymmarkov @attila-at-hyper

**Comment by zenangst** [comment]
I kinda like how the last function call reads. It is very readable and describes its intent.

**Comment by RamonGilabert** [comment]
It is actually free in Cocoapods, don't understand why. :smile: but yes, I agree, Keychain makes more sense. It's clearer.

**Comment by zenangst** [comment]
My vote is on `Keychain`, what about you @vadymmarkov ?

**Comment by vadymmarkov** [comment]
+1 for `Keychain`

**Comment by vadymmarkov** [comment]
And default service is also a good idea.

**Comment by zenangst** [comment]
@vadymmarkov @RamonGilabert made a pull request :grin:

**Comment by RamonGilabert** [comment]
Closing as #3 is merged.
